package counters;

public enum CounterType {
    ADS_TOPICS,
    BLACK_LIST,
    CATALOGS,
    DELAYED_TOPICS,
    JOIN_REQUESTS,
    LINKS,
    MAYBE,
    MEMBERS,
    MODERATORS,
    MUSIC_TRACKS,
    OWN_PRODUCTS,
    PHOTOS,
    PHOTO_ALBUMS,
    PINNED_TOPICS,
    PRESENTS,
    PRODUCTS,
    PROMO_TOPICS_ON_MODERATION,
    SUGGESTED_PRODUCTS,
    SUGGESTED_TOPICS,
    THEMES,
    UNPUBLISHED_TOPICS,
    VIDEOS
}
